### ISSUE TITLE
0publish returns error on xmlsign

### ISSUE THREAD

**Issue by basiliscos** [0install/0publish#5]
`0publish -x myapp-1.0.0.xml`

```
Traceback (most recent call last):
  File "/home/b/.cache/0install.net/implementations/sha256new_7LKYTUQ3Y24PQV2BX3B3CNYLTH4SSEKRP7F7YIJSQSA3A7EKDU3Q/0publish", line 200, in <module>
    sign_fn(interface, data, key)
  File "/home/b/.cache/0install.net/implementations/sha256new_7LKYTUQ3Y24PQV2BX3B3CNYLTH4SSEKRP7F7YIJSQSA3A7EKDU3Q/signing.py", line 77, in sign_xml
    encoded = base64.encodestring(stream.read())
AttributeError: module 'base64' has no attribute 'encodestring'
```

**Comment by backlabs1** [comment]
I encountered this problem also. `encodestring()` is an alias of `encodebytes()` and has been deprecated since Python 3.1; see the [Python 3.8 base64 documentation](https://docs.python.org/3.8/library/base64.html#base64.encodestring).

The now-missing `encodestring()` is only used at [signing.py#77](https://github.com/0install/0publish/blob/96e56402bb4c6fd72657c679e710def0edfa1f8e/signing.py#L77).

Pull request #7 includes the fix but it unfortunately is combined with a new feature.

Would a pull request for this single-line fix be accepted?
